# Generated by Django 4.2.2 on 2023-07-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odmapp', '0004_donar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donar',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
